// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqSjXU4LpYphDOXDpbtqpgY0p_oabXQ54',
    appId: '1:2558593964:web:8543d1f2525f01ed2cc809',
    messagingSenderId: '2558593964',
    projectId: 'naturaai',
    authDomain: 'naturaai.firebaseapp.com',
    storageBucket: 'naturaai.firebasestorage.app',
    measurementId: 'G-3QHLNDBBW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUYTv1P_seG1db3hhJyUB1JiqXXpJf6U',
    appId: '1:2558593964:android:6c4d483307eb7b292cc809',
    messagingSenderId: '2558593964',
    projectId: 'naturaai',
    storageBucket: 'naturaai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6VulCjr-q5cTpvJfUz1NeeUScR9NOUmQ',
    appId: '1:2558593964:ios:c3829c06283490f02cc809',
    messagingSenderId: '2558593964',
    projectId: 'naturaai',
    storageBucket: 'naturaai.firebasestorage.app',
    iosBundleId: 'uz.srvr.naturaai',
  );
}
