name: APK Size Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  apk-size:
    name: Generate APK Size Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Report APK Size
        uses: martinroob/apk-size@v1
        with:
            apkPath: build/app/outputs/flutter-apk/app-release.apk