name: Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers only when you push a tag like v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Decode and write google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_B64 }}" | base64 -d > android/app/google-services.json
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get
      - name: Install Android NDK 27
        run: sdkmanager "ndk:27.0.12077973"
      
      - name: Build APK
        run: flutter build apk --release

      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}